config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :campaigns do
    member do
      get :data
    end

    resources :ads do
      member do
        get :data
      end
    end
  end

  root 'campaigns#index'
end

app/models/ad.rb
class Ad < ActiveRecord::Base
  multi_tenant :company

  belongs_to :campaign
  has_many :clicks, dependent: :delete_all
  has_many :impressions, dependent: :delete_all
end

app/controllers/ads_controller.rb
class AdsController < ApplicationController
  def show
    @ad = Ad.find(params[:id])
  end

  def data
    @ad = Ad.find(params[:id])

    start_ts = Time.at(params['start'].to_i).utc.beginning_of_day
    end_ts   = Time.at(params['end'].to_i).utc.end_of_day

    impressions_by_day = Impression.where(seen_at: start_ts..end_ts, ad_id: @ad.id)
                         .order("2").group("extract(epoch from date_trunc('day', seen_at))").count

    clicks_by_day = Click.where(clicked_at: start_ts..end_ts, ad_id: @ad.id)
                    .order("2").group("extract(epoch from date_trunc('day', clicked_at))").count

    ctr_by_day = {}
    impressions_by_day.each do |day, impressions|
      ctr_by_day[day] = (clicks_by_day[day] || 0) / impressions.to_f * 100
    end

    data = {
      "Impressions" => impressions_by_day.to_a,
      "Clicks" => clicks_by_day.to_a,
      "Click-Through Rate" => ctr_by_day.to_a,
    }
    render json: data, callback: params[:callback]
  end
end

app/views/ads/show.html.erb
<% content_for(:title) { "Ad \"#{@ad.name}\"" } %>
<% content_for(:description) { "ID #{@ad.id}" } %>

<div class="row">
  <div class="col-md-12">
    <div class="box">
      <div id="stats" style="width: 99%" class="datagraph"></div>
    </div>

    <div class="box">
      <div class="box-header with-border">
        <h3 class="box-title">Last 10 Impressions</h3>
      </div>
      <div class="box-body">
        <table class="table table-bordered">
          <tr>
            <th style="width: 10px">#</th>
            <th>Site URL</th>
            <th>IP</th>
            <th>Location</th>
            <th>Mobile?</th>
            <th>Seen At</th>
            <th>Cost Per Impression</th>
          </tr>
          <% @ad.impressions.order('seen_at DESC').limit(10).each do |impression| %>
            <tr>
              <td><%#= impression.id[/^\w+/] %></td>
              <td><%= impression.site_url %></td>
              <td><%= impression.user_ip %></td>
              <td><%= impression.user_data['location'] %></td>
              <td><%= impression.user_data['is_mobile'] ? 'Yes' : 'No' %></td>
              <td><%= impression.seen_at %></td>
              <td><%= @ad.campaign.cost_model == 'cost_per_impression' ? impression.cost_per_impression_usd : 'n/a' %></td>
            </tr>
          <% end %>
        </table>
      </div>
    </div>

    <div class="box">
      <div class="box-header with-border">
        <h3 class="box-title">Last 10 Clicks</h3>
      </div>
      <div class="box-body">
        <table class="table table-bordered">
          <tr>
            <th style="width: 10px">#</th>
            <th>Site URL</th>
            <th>IP</th>
            <th>Location</th>
            <th>Mobile?</th>
            <th>Seen At</th>
            <th>Cost Per Click</th>
          </tr>
          <% @ad.clicks.order('clicked_at DESC').limit(10).each do |click| %>
            <tr>
              <td><%#= click.id[/^\w+/] %></td>
              <td><%= click.site_url %></td>
              <td><%= click.user_ip %></td>
              <td><%= click.user_data['location'] %></td>
              <td><%= click.user_data['is_mobile'] ? 'Yes' : 'No' %></td>
              <td><%= click.clicked_at %></td>
              <td><%= @ad.campaign.cost_model == 'cost_per_click' ? click.cost_per_click_usd : 'n/a' %></td>
            </tr>
          <% end %>
        </table>
      </div>
    </div>
  </div>
</div>

<script type="text/javascript">
new PG.DataGraph("#stats.datagraph", "<%= data_campaign_ad_path(@ad.campaign, @ad) %>", {
  defaultDuration: 30,
  detailSmoothing: 1,
  overviewSmoothing: 1,
  datePickers: [
    { label: "last 90 days",  duration: 90 },
    { label: "last 60 days",  duration: 60 },
    { label: "last 30 days", duration: 30 }
  ],
});
</script>